return {
    ["RobloxClassic"] = {
        ["R15"] = "rbxassetid://7430070993"
    },
    ["Blockhead"] = {
        ["R15"] = "https://www.roblox.com/asset/?id=5560742512",
        ["R6"] = "https://www.roblox.com/asset/?id=5560742512"
    },
    ["Cheeks"] = {
        ["R15"] = "https://assetdelivery.roblox.com/v1/asset/?id=13916684351",
        ["R6"] = "https://assetdelivery.roblox.com/v1/asset/?id=13916684351"
    },
    ["Chiseled"] = {
        ["R15"] = "rbxassetid://8635368660",
        ["R6"] = "rbxassetid://8635368660"
    },
    ["CoolThing"] = {
        ["R15"] = "https://www.roblox.com/asset/?id=5591363019",
        ["R6"] = "https://www.roblox.com/asset/?id=5591363019"
    },
    ["EraserHead"] = {
        ["R15"] = "https://www.roblox.com/asset/?id=5591363284",
        ["R6"] = "https://www.roblox.com/asset/?id=5591363284"
    },
    ["FatHead"] = {
        ["R15"] = "https://www.roblox.com/asset/?id=5591374083",
        ["R6"] = "https://www.roblox.com/asset/?id=5591374083"
    },
    ["FlatTop"] = {
        ["R15"] = "https://www.roblox.com/asset/?id=5591363456",
        ["R6"] = "https://www.roblox.com/asset/?id=5591363456"
    },
    ["GoldenKorbloxGeneral"] = {
        ["R15"] = "https://assetdelivery.roblox.com/v1/asset/?id=6678805742",
        ["R6"] = "https://assetdelivery.roblox.com/v1/asset/?id=6678805742"
    },
    ["GoldenMrRobot"] = {
        ["R15"] = "https://assetdelivery.roblox.com/v1/asset/?id=7976777570",
        ["R6"] = "https://assetdelivery.roblox.com/v1/asset/?id=7976777570"
    },
    ["KnightOfChivalry"] = {
        ["R15"] = "http://www.roblox.com/asset/?id=2507439407",
        ["R6"] = "http://www.roblox.com/asset/?id=2507439407"
    },
    ["KnightOfCourage"] = {
        ["R15"] = "http://www.roblox.com/asset/?id=2533371313",
        ["R6"] = "http://www.roblox.com/asset/?id=2533371313"
    },
    ["ManHead"] = {
        ["R15"] = "rbxassetid://8635368147",
        ["R6"] = "rbxassetid://8635368147"
    },
    ["MercilessNinja"] = {
        ["R15"] = "https://assetdelivery.roblox.com/v1/asset/?id=6652967864",
        ["R6"] = "https://assetdelivery.roblox.com/v1/asset/?id=6652967864"
    },
    ["Narrow"] = {
        ["R15"] = "rbxassetid://8635369445",
        ["R6"] = "rbxassetid://8635369445"
    },
    ["Paragon"] = {
        ["R15"] = "rbxassetid://8635368843",
        ["R6"] = "rbxassetid://8635368843"
    },
    ["Peabrain"] = {
        ["R15"] = "rbxassetid://8635365143",
        ["R6"] = "rbxassetid://8635365143"
    },
    ["Perfection"] = {
        ["R15"] = "https://www.roblox.com/asset/?id=5591363762",
        ["R6"] = "https://www.roblox.com/asset/?id=5591363762"
    },
    ["Roll"] = {
        ["R15"] = "https://www.roblox.com/asset/?id=5591363641",
        ["R6"] = "https://www.roblox.com/asset/?id=5591363641"
    },
    ["Roundy"] = {
        ["R15"] = "https://assetdelivery.roblox.com/v1/asset/?id=10382778666",
        ["R6"] = "https://www.roblox.com/asset/?id=5560742556"
    },
    ["RoxBox"] = {
        ["R15"] = "https://www.roblox.com/asset/?id=5591363588",
        ["R6"] = "https://www.roblox.com/asset/?id=5591363588"
    },
    ["TheEngineer"] = {
        ["R15"] = "https://assetdelivery.roblox.com/v1/asset/?id=6711195585",
        ["R6"] = "https://assetdelivery.roblox.com/v1/asset/?id=6711195585"
    },
    ["Trim"] = {
        ["R15"] = "https://www.roblox.com/asset/?id=5560742658",
        ["R6"] = "https://www.roblox.com/asset/?id=5560742658"
    },
    ["WomanHead"] = {
        ["R15"] = "rbxassetid://8635368421",
        ["R6"] = "rbxassetid://8635368421"
    }
}